### ISSUE TITLE
Dossiers de traduction "/res/values-fr-rFR/"

### ISSUE THREAD

**Issue by KevinMinions** [DelphinPETER/TranslationTools#182]
Bonjour Delphin PETER,
Pour certaines applications, le dossier de fichier de traduction se trouve dans un dossier sous la forme de "/res/values-fr-rFR/"

Par exemple : https://github.com/DirtyUnicorns/android_packages_apps_SettingsIntelligence/tree/p9x/res

Du coup, TranslationTools indique les chaînes comme non traduites.
Existe t-il une possibilité technique pour que TranslationTools prenne en compte les dossiers de fichier de traduction sous la forme "/res/values-[code langue]-r[CODE LANGUE]/" ?

Merci et bonne journée.

**Comment by DelphinPETER** [comment]
Bonjour, il faudrait tester avec la fonction qui permet de fusionner 2 langues.
Dans ce cas, la langue fr-rFR viens compléter la langue FR et cela prend donc en compte les deux.
Comme pour la langue pt-rBR
https://github.com/DelphinPETER/TranslationTools/commit/b500471c3db43665af7017fbc80c5232fdc863a3

Attention j'ai fais la modification sur la branche DU80 et c'était peut-être sur la DU90 qu'il fallait le faire.

**Comment by KevinMinions** [comment]
Oui, c'est pour du90.

**Comment by KevinMinions** [comment]
Ça fonctionne parfaitement.
Merci Delphin.
Je suis en train de préparer le fichier TranslationTools/config/config.xml avec l'ajout de toutes les langues.
Une fois terminé, je l'enverrai sur DU90.
