### ISSUE TITLE
Création d'une nouvelle bracnhe

### ISSUE THREAD

**Issue by KevinMinions** [DelphinPETER/TranslationTools#193]
Bonjour Delphin,
J'espère que vous (et vos proches) allez bien.

À l'occasion, pourriez-vous créer une branche du11, s'il vous plaît ?

Bonne journée à vous.

**Comment by DelphinPETER** [comment]
Bonjour, ça va merci. J'espère que pour vous aussi.
Normalement c'est tout bon pour du11 !

**Comment by KevinMinions** [comment]
Merci, impeccable, et oui ;-)
